import { LeagueInfo } from '../types';

export const SUPPORTED_LEAGUES: LeagueInfo[] = [
  {
    id: 'soccer-all-monitored',
    name: 'All Monitored Competitions',
    sport: 'soccer',
    slug: 'monitored-all',
    category: 'All',
    icon: 'Trophy',
  },
  {
    id: 'soccer-eng1',
    name: 'English Premier League',
    sport: 'soccer',
    slug: 'eng.1',
    category: 'England',
    icon: 'Shield',
  },
  {
    id: 'soccer-esp1',
    name: 'Spanish LaLiga',
    sport: 'soccer',
    slug: 'esp.1',
    category: 'Spain',
    icon: 'Flame',
  },
  {
    id: 'soccer-ita1',
    name: 'Italian Serie A',
    sport: 'soccer',
    slug: 'ita.1',
    category: 'Italy',
    icon: 'Shield',
  },
  {
    id: 'soccer-ger1',
    name: 'German Bundesliga',
    sport: 'soccer',
    slug: 'ger.1',
    category: 'Germany',
    icon: 'Shield',
  },
  {
    id: 'soccer-fra1',
    name: 'French Ligue 1',
    sport: 'soccer',
    slug: 'fra.1',
    category: 'France',
    icon: 'Compass',
  },
  {
    id: 'soccer-ucl',
    name: 'UEFA Champions League',
    sport: 'soccer',
    slug: 'uefa.champions',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-uel',
    name: 'UEFA Europa League',
    sport: 'soccer',
    slug: 'uefa.europa',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-uecl',
    name: 'UEFA Europa Conference League',
    sport: 'soccer',
    slug: 'uefa.europa.conf',
    category: 'Europe',
    icon: 'Trophy',
  },
  {
    id: 'soccer-usa1',
    name: 'Major League Soccer',
    sport: 'soccer',
    slug: 'usa.1',
    category: 'Americas',
    icon: 'Compass',
  },
  {
    id: 'soccer-libertadores',
    name: 'Copa Libertadores',
    sport: 'soccer',
    slug: 'conmebol.libertadores',
    category: 'Americas',
    icon: 'Trophy',
  },
  {
    id: 'soccer-fifa',
    name: 'FIFA World Cup',
    sport: 'soccer',
    slug: 'fifa.world',
    category: 'International',
    icon: 'Trophy',
  },
  {
    id: 'soccer-engfa',
    name: 'English FA Cup',
    sport: 'soccer',
    slug: 'eng.fa',
    category: 'England',
    icon: 'Award',
  },
  {
    id: 'soccer-engcup',
    name: 'English Carabao Cup',
    sport: 'soccer',
    slug: 'eng.league_cup',
    category: 'England',
    icon: 'Award',
  },
  {
    id: 'soccer-espcopadelrey',
    name: 'Spanish Copa del Rey',
    sport: 'soccer',
    slug: 'esp.copa_del_rey',
    category: 'Spain',
    icon: 'Award',
  },
  {
    id: 'soccer-ned1',
    name: 'Dutch Eredivisie',
    sport: 'soccer',
    slug: 'ned.1',
    category: 'Netherlands',
    icon: 'Shield',
  },
  {
    id: 'soccer-por1',
    name: 'Portuguese Primeira Liga',
    sport: 'soccer',
    slug: 'por.1',
    category: 'Portugal',
    icon: 'Shield',
  },
  {
    id: 'soccer-sau1',
    name: 'Saudi Pro League',
    sport: 'soccer',
    slug: 'sau.1',
    category: 'Middle East',
    icon: 'Award',
  },
];

export const MONITORED_LEAGUE_SLUGS = [
  'eng.1',
  'esp.1',
  'ita.1',
  'ger.1',
  'fra.1',
  'uefa.champions',
  'uefa.europa',
  'uefa.europa.conf',
  'usa.1',
  'conmebol.libertadores',
  'fifa.world',
  'eng.fa',
  'eng.league_cup',
  'esp.copa_del_rey',
  'ned.1',
  'por.1',
  'sau.1',
];
